// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAVNuEQh-WB-I9aFq-4p6A54B_aik0mSs',
    appId: '1:583962742465:web:e728d67ffa51366bf38e40',
    messagingSenderId: '583962742465',
    projectId: 'cavapremium-31036',
    authDomain: 'cavapremium-31036.firebaseapp.com',
    storageBucket: 'cavapremium-31036.firebasestorage.app',
    measurementId: 'G-D75NN4Z9FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl0tHQTVvg2StcNSKyK4xRraCvhyqfTeY',
    appId: '1:583962742465:android:ad194ce8f73edcf8f38e40',
    messagingSenderId: '583962742465',
    projectId: 'cavapremium-31036',
    storageBucket: 'cavapremium-31036.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVGhRW3GvjidPyBsRxkSa0e-vn7ufv4qc',
    appId: '1:583962742465:ios:8a309b7b226531d1f38e40',
    messagingSenderId: '583962742465',
    projectId: 'cavapremium-31036',
    storageBucket: 'cavapremium-31036.firebasestorage.app',
    iosBundleId: 'com.example.cavaEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVGhRW3GvjidPyBsRxkSa0e-vn7ufv4qc',
    appId: '1:583962742465:ios:8a309b7b226531d1f38e40',
    messagingSenderId: '583962742465',
    projectId: 'cavapremium-31036',
    storageBucket: 'cavapremium-31036.firebasestorage.app',
    iosBundleId: 'com.example.cavaEcommerce',
  );
}
